### ISSUE TITLE
While installing xml-stream module using npm-install module getting below error message

### ISSUE THREAD

**Issue by baveja** [apigeecs/apigee-jsc-debug#2]
gyp ERR! build error
gyp ERR! stack Error: Command failed: C:\windows\system32\cmd.exe /s /c "reg que
ry "HKLM\Software\Microsoft\MSBuild\ToolsVersions" /s /reg:32"
gyp ERR! stack 'reg' is not recognized as an internal or external command,
gyp ERR! stack operable program or batch file.
gyp ERR! stack
gyp ERR! stack Can't find "msbuild.exe". Do you have Microsoft Visual Studio C++
 2008+ installed?
gyp ERR! stack     at c:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\build.js:134:25
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:220:5)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:829:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:211:5)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "c:\Program Files\nodejs\node.exe" "c:\Program Files\nodej
s\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd c:\Users\mohit.baveja\Desktop\apigee-jsc-debug\sampleProxy\24Solver
\tests\debug\node_modules\xml-stream\node_modules\node-expat
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

> iconv@2.2.1 install c:\Users\mohit.baveja\Desktop\apigee-jsc-debug\sampleProxy
> \24Solver\tests\debug\node_modules\xml-stream\node_modules\iconv
> node-gyp rebuild

c:\Users\mohit.baveja\Desktop\apigee-jsc-debug\sampleProxy\24Solver\tests\debug\
node_modules\xml-stream\node_modules\iconv>if not defined npm_config_node_gyp (n
ode "c:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modul
es\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp ERR! build error
gyp ERR! stack Error: Command failed: C:\windows\system32\cmd.exe /s /c "reg que
ry "HKLM\Software\Microsoft\MSBuild\ToolsVersions" /s /reg:32"
gyp ERR! stack 'reg' is not recognized as an internal or external command,
gyp ERR! stack operable program or batch file.
gyp ERR! stack
gyp ERR! stack Can't find "msbuild.exe". Do you have Microsoft Visual Studio C++
 2008+ installed?
gyp ERR! stack     at c:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\build.js:134:25
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:220:5)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:829:16)

**Comment by TRSKY** [comment]
Did you figure this out ? I have the same issue while running npm install in a rails app

**Comment by davidwallen** [comment]
Build for xml-stream on Windows has dependencies on some optional components or a full install of VS2007. You should see this error just installing xml-stream as well.
